    # ---------- Stage 1: Build React App ----------
    FROM node:20-alpine AS build

    WORKDIR /app

    # copy dependency files first (for caching)
    COPY package*.json ./
    RUN npm install

    # copy source code
    COPY . .

    # build production static files
    RUN npm run build
    
   

    # ---------- Stage 2: Serve using Nginx ----------
    FROM nginx:alpine

    RUN addgroup -S appgroup && adduser -S appuser -G appgroup
    # remove default nginx website
    RUN rm -rf /usr/share/nginx/html/*

    # copy built files from previous stage
    COPY --from=build /app/build /usr/share/nginx/html
    
    RUN chown -R appuser:appgroup /usr/share/nginx/html

    USER appuser
    # expose web port
    EXPOSE 80

    # start nginx
    CMD ["nginx", "-g", "daemon off;"]


